include_defs('//bucklets/maven_jar.bucklet')

maven_jar(
  name = 'dbcp',
  id = 'commons-dbcp:commons-dbcp:1.4',
  sha1 = '30be73c965cc990b153a100aaaaafcf239f82d39',
  license = 'Apache2.0',
  exclude = [
    'META-INF/LICENSE.txt',
    'META-INF/NOTICE.txt',
    'testpool.jocl'
  ],
)

